name: Test Web
on:
  push:
    branches:
      - develop
      - feat/workflow
    paths:
      - web/src/**
jobs:
  run-jets-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Actions
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd web && npm run test

      - name: Run jest script
        run: npm run test
