name: Test Web
on:
  push:
    branches:
      - develop

    paths:
      - web/src/**
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Actions
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd web && npm install

      - name: Run jest script
        run: npm run test
